"""changes in careevent, enum decisions, dates

Revision ID: 009d66aac850
Revises: 6185b59de07f
Create Date: 2026-09-25 00:32:58.944882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '009d66aac850'
down_revision: Union[str, Sequence[str], None] = '6185b59de07f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('care_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('WATERING', 'FERTILIZING', 'REPOTTING', 'HARVESTING', 'SOWING', 'ACQUIRED', 'TRIMMING', name='eventtype', native_enum=False), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('plants', sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plants', 'created_at')
    op.drop_table('care_events')
    # ### end Alembic commands ###
