"""updated plants with a name column

Revision ID: 6185b59de07f
Revises: b43039262c96
Create Date: 2026-09-24 23:50:15.868379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6185b59de07f'
down_revision: Union[str, Sequence[str], None] = 'b43039262c96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plants', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plants', 'name')
    # ### end Alembic commands ###
